#!/bin/bash

## VPN available host index.html creator.

# Get the list of available VPN IPs from the wg-only-HS-IP script
vpnIPs=$(/var/www/html/wg-only-HS-IP)

# Loop through each IP address and determine the hostname
while read -r ip; do
  hostname=$(host "$ip" | awk '{print $5}' | sed 's/.$//')
  if [[ $hostname ]]; then
    hostnames+=("$hostname")
  fi
done < <(echo "$vpnIPs")

# Generate the index.html
{
    echo '<!DOCTYPE html>'
    echo '<html>'
    echo '<head>'
    echo '<title>Available Webmin Hosts</title>'
    echo '</head>'
    echo '<body>'
    echo '<h1>Available Webmin Hosts</h1>'
    echo '<ul>'
    for hostname in "${hostnames[@]}"; do
        if [[ ! "$hostname" =~ "mob" ]]; then
            echo "<li><a href=\"https://${hostname}/\">https://${hostname}/</a></li>"
        fi
    done
    echo '</ul>'
    echo '</body>'
    echo '</html>'
} > /var/www/html/index.html
