#!/bin/bash

# get the handshaked VPN IPs
output=$(/var/www/wingarmac.org/vpnIP)

# Filter the output to find domain names containing "ns1" or "ns2"
vpnIPs=$(echo "$output" | grep "vpn")

# Generate the index.html
{
    echo '<!DOCTYPE html>'
    echo '<html>'
    echo '<link rel="stylesheet" type="text/css" href="./theme.css">'
    echo '<body>'
    # Available Webmin Hosts section
    echo '<header style="color: white; background-color: #254a93;">'
    echo '<h1>Available Webmin Hosts</h1>'
    echo '</header>'
    echo '<div class="container webmin-hosts">'
    echo '<ul class="links">'
    while read -r hostname; do
    fqdn="${hostname/vpn/org}"
shortname=$(echo "$fqdn" | cut -d '.' -f 1)
echo "<div class='webmin-host'><a href=\"https://${fqdn}/\"><img class=\"webmin-icon\" src=\"wpc.png\"></a><span class=\"host\"><a href=\"https://${fqdn}/\">${shortname}</a></span></div>"
    done <<< "$vpnIPs"
    echo '</ul>'
    echo '</div>'
    echo '</div>'
    echo '<header style="color: green; background-color: white;">'
    echo '<h2>Available SSH Hosts</h2>'
    echo '</header>'
    echo '<div class="container ssh-hosts">'
    echo '<ul class="ssh-list">'
    while read -r hostname; do
        if [[ "$hostname" == *"ubcynt"* ]]; then
            continue  # skip this hostname
        fi
        fqdn="${hostname}"
        if [[ "$fqdn" == *"wingarmac"* ]]; then
            echo "<li><img class=\"ssh-icon\" src=\"term.png\"><a href=\"ssh://${hostname}\">${fqdn}</a></li>"
        fi
    done <<< "$vpnIPs"
    echo '</ul>'
    echo '</div>'
    echo '</body>'
    echo '</html>'
} > /var/www/wingarmac.org/index.html
