#!/bin/bash

# Get the server's IP address
server_ip=$(ip -4 addr show dev wg0 | awk '/inet/ {print $2}' | cut -d '/' -f 1)

# Get the list of WireGuard IPs
wg show wg0 | awk '/allowed ips/ {for (i=1; i<=NF; i++) {split($i, parts, "/"); if (parts[1] ~ /^10\.5\.5\.[0-9]{1,3}$/ && parts[1] != "10.5.5.0") print parts[1]}}' > temp_ips.txt

# Get the second server's IP from wg0.conf
second_server_ip=$(sed -n 's/^DNS = \(.*\)$/\1/p' /etc/wireguard/wg0.conf)

# Add server's IP
echo "$server_ip" > temp_ips.txt
echo "$second_server_ip" >> temp_ips.txt

# Filter out IPs between 10.5.5.100 and 10.5.5.200
filtered_ips=$(sed -i '/^10\.5\.5\.\(10[0-9]\|1[0-9][0-9]\|200\)$/d' temp_ips.txt)

# Read the filtered IPs into an array
readarray -t filtered_ips < temp_ips.txt

# Ping each IP to verify if they are connected
connected_ips=""
for ip in "${filtered_ips[@]}"; do
    if ping -c 1 -W 1 "$ip" >/dev/null; then
        connected_ips+="$ip"$'\n'
    fi
done

# Print the final result
echo "$connected_ips"

# Cleanup temporary files
rm temp_ips.txt
